package id.my.hendisantika.accountingsample.dto.journal;

import id.my.hendisantika.accountingsample.model.enums.JournalEntryStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Created by IntelliJ IDEA.
 * Project : accounting-sample
 * User: hendisantika
 * Link: s.id/hendisantika
 * Email: hendisantika@yahoo.co.id
 * Telegram : @hendisantika34
 * Date: 16/10/25
 * Time: 13.45
 * To change this template use File | Settings | File Templates.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class JournalEntryResponse {

    private Long id;
    private String journalNumber;
    private LocalDate entryDate;
    private JournalEntryStatus status;
    private String reference;
    private String description;
    private BigDecimal totalDebit;
    private BigDecimal totalCredit;
    private Boolean isAutoGenerated;
    private List<JournalEntryLineResponse> lines;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class JournalEntryLineResponse {
        private Long id;
        private Long accountId;
        private String accountCode;
        private String accountName;
        private String description;
        private BigDecimal debitAmount;
        private BigDecimal creditAmount;
        private Integer lineOrder;
    }
}
